# Generated by Django 3.1.4 on 2020-12-19 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urldata',
            name='slug',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
