# Generated by Django 3.1.4 on 2020-12-20 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0002_auto_20201219_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='urldata',
            name='shorturl',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='urldata',
            name='url',
            field=models.CharField(max_length=800),
        ),
    ]
