# Generated by Django 3.1.4 on 2020-12-20 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0003_auto_20201220_1259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urldata',
            old_name='shorturl',
            new_name='short_url',
        ),
    ]
