# Generated by Django 3.1.4 on 2020-12-20 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0005_remove_urldata_short_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='urldata',
            name='domain',
            field=models.CharField(max_length=800, null=True),
        ),
    ]
